version: '3.7'

services:
  oracle-db:
    container_name: apidb
    hostname: apidb
    image: gvenzl/oracle-xe:18-slim
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PASSWORD=oracle
    volumes:
       - .docker/oradata/oradata/:/opt/oracle/oradata
    healthcheck:
      test: ["CMD", "sqlplus", "-s", "/ as sysdba", "<<<", "SELECT 1 FROM DUAL;"]
      interval: 30s
      timeout: 10s
      retries: 3


networks:
  default:
    name: service_sample
